# Generated by Django 5.1.4 on 2025-01-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='craftsman',
            old_name='skills',
            new_name='skill',
        ),
        migrations.RemoveField(
            model_name='craftsman',
            name='surname',
        ),
        migrations.AddField(
            model_name='apprentice',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='craftsman',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
